### PR TITLE
Implement list add command

### PR DESCRIPTION
**Pull request by iamwillzhu**
# Description

Added the 'list add' command and updated the interface to show the `list add` option

# Related Issues
https://github.com/qcam/3llo/issues/68

# Manual Testing Plan
Did a manual test on the CLI after rebuilding gem 

Added an integration spec for `list add` but I am unfamiliar with ruby and don't know how to set up the testing environment

### CODE REVIEW

**Comment by iamwillzhu** [comment]
sorry for the bloated commits. I'll squash them once merged

**Comment by iamwillzhu** [comment]
Also I'm wondering how do you run the integration tests on local? When I run `bundle exec rspec` I get these results
Screen Shot 2020-04-13 at 11 38 23 PM

**Comment by diepsohung** [comment]
Please run it on your local machine so that you can run the integration tests.
`docker run -d -p 8080:80 kennethreitz/httpbin` @iamwillzhu

**Comment by iamwillzhu** [comment]
squashed all commits

**Pull request merged**
